#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2014, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# clone fe:SOURCE host:remote_system_ds/disk.i size
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host

SRC=$1
DST=$2
VM_ID=$3
DS_ID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON

DST_HOST=`arg_host $DST`
SRC_PATH=`arg_path $SRC`

#-------------------------------------------------------------------------------
# Compute the destination image name
#-------------------------------------------------------------------------------

DISK_ID=$(echo $DST|awk -F. '{print $NF}')
SHEEPDOG_DST="${SRC_PATH}-${VM_ID}-${DISK_ID}"
SHEEPDOG_SNAP="$( basename $0 )_${VM_ID}-${DISK_ID}"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VM_ID| $XPATH \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SHEEPDOG_HOST)

SHEEPDOG_HOST="${XPATH_ELEMENTS[j++]}"
if [ -z "$SHEEPDOG_HOST" ]; then
    SHEEPDOG_HOST="127.0.0.1"
fi

#-------------------------------------------------------------------------------
# Clone the image
#-------------------------------------------------------------------------------

CLONE_CMD=$(cat <<EOF
set -e

sudo $DOG vdi snapshot -a $SHEEPDOG_HOST -s $SHEEPDOG_SNAP $SRC_PATH
sudo $DOG vdi clone -a $SHEEPDOG_HOST -s $SHEEPDOG_SNAP $SRC_PATH $SHEEPDOG_DST
sudo $DOG vdi delete -a $SHEEPDOG_HOST -s $SHEEPDOG_SNAP $SRC_PATH

EOF
)

ssh_exec_and_log "$DST_HOST" "$CLONE_CMD" \
        "Error cloning $SRC_PATH to $SHEEPDOG_DST in $DST_HOST"
exit 0
